In [45]:
%matplotlib inline
import os
import sys
import IPython.display as ipd
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as skl
import sklearn.utils, sklearn.preprocessing, sklearn.decomposition, sklearn.svm
import librosa
import librosa.display

import utils

In [ ]:
from keras.datasets import mnist

In [46]:
#functions of non-linear activations
def f_sigmoid(X, deriv=False):
    if not deriv:
        return 1 / (1 + np.exp(-X))
    else:
        return f_sigmoid(X)*(1 - f_sigmoid(X))


def f_softmax(X):
    Z = np.sum(np.exp(X), axis=1)
    Z = Z.reshape(Z.shape[0], 1)
    return np.exp(X) / Z


def f_relu(X):
    return np.maximum(0,X)


In [47]:
def exit_with_err(err_str):
    print(sys.stderr, err_str)
    sys.exit(1)

In [48]:
#Functionality of a single hidden layer
class Layer:
    def __init__(self, size, batch_size, is_input=False, is_output=False,
                 activation=f_sigmoid):
        self.is_input = is_input
        self.is_output = is_output

        # Z is the matrix that holds output values
        self.Z = np.zeros((batch_size, size[0]))
        # The activation function is an externally defined function (with a
        # derivative) that is stored here
        self.activation = activation

        # W is the outgoing weight matrix for this layer
        self.W = None
        # S is the matrix that holds the inputs to this layer
        self.S = None
        # D is the matrix that holds the deltas for this layer
        self.D = None
        # Fp is the matrix that holds the derivatives of the activation function
        self.Fp = None

        if not is_input:
            self.S = np.zeros((batch_size, size[0]))
            self.D = np.zeros((batch_size, size[0]))

        if not is_output:
            self.W = np.random.normal(size=size, scale=1E-4)

        if not is_input and not is_output:
            self.Fp = np.zeros((size[0], batch_size))

    def forward_propagate(self):
        if self.is_input:
            return self.Z.dot(self.W)

        self.Z = self.activation(self.S)
        if self.is_output:
            return self.Z
        else:
            # For hidden layers, we add the bias values here
            self.Z = np.append(self.Z, np.ones((self.Z.shape[0], 1)), axis=1)
            self.Fp = self.activation(self.S, deriv=True).T
            return self.Z.dot(self.W)


In [49]:
class MultiLayerPerceptron:
    def __init__(self, layer_config, batch_size=100,activation_o = f_softmax):
        self.layers = []
        self.num_layers = len(layer_config)
        self.minibatch_size = batch_size

        for i in range(self.num_layers-1):
            if i == 0:
                print ("Initializing input layer with size {0}.".format(layer_config[i]))
                # Here, we add an additional unit at the input for the bias
                # weight.
                self.layers.append(Layer([layer_config[i]+1, layer_config[i+1]],
                                         batch_size,
                                         is_input=True))
            else:
                print ("Initializing hidden layer with size {0}.".format(layer_config[i]))
                # Here we add an additional unit in the hidden layers for the
                # bias weight.
                self.layers.append(Layer([layer_config[i]+1, layer_config[i+1]],
                                         batch_size,
                                        activation=f_sigmoid))


        print ("Initializing output layer with size {0}.".format(layer_config[-1]))
        self.layers.append(Layer([layer_config[-1], None],
                                 batch_size,
                                 is_output=True,
                                 activation=activation_o))
        print ("Done!")

    def forward_propagate(self, data):
        # We need to be sure to add bias values to the input
        self.layers[0].Z = np.append(data, np.ones((data.shape[0], 1)), axis=1)

        for i in range(self.num_layers-1):
            self.layers[i+1].S = self.layers[i].forward_propagate()
        return self.layers[-1].forward_propagate()

    def backpropagate(self, yhat, labels):
        
        #Check!
        #exit_with_err("FIND ME IN THE CODE, What is computed in the next line of code?\n")
        
        #The differnce between the predicted labels from the neural network and the correct labels
        #Calculates the derivate of the cost function
        self.layers[-1].D = (yhat - labels).T
        
        for i in range(self.num_layers-2, 0, -1):
            # We do not calculate deltas for the bias values
            W_nobias = self.layers[i].W[0:-1, :]
            
           #exit_with_err("FIND ME IN THE CODE, What does this 'for' loop do?\n")
            
            #Backpropagates the delta with respect to the derivate of the activation function
            #Bakcpropagates the partial derivates
            self.layers[i].D = W_nobias.dot(self.layers[i+1].D) * self.layers[i].Fp

    def update_weights(self, eta):
        for i in range(0, self.num_layers-1):
            #Delta is used to know how the weights should be adjusted to minimize the error
            W_grad = -eta*(self.layers[i+1].D.dot(self.layers[i].Z)).T
            self.layers[i].W += W_grad

    def evaluate(self, train_data, train_labels, test_data, test_labels,
                 num_epochs=70, eta=0.05, eval_train=False, eval_test=True):

        N_train = len(train_labels)*len(train_labels[0])
        N_test = len(test_labels)*len(test_labels[0])

        print ("Training for {0} epochs...".format(num_epochs))
        for t in range(0, num_epochs):
            out_str = "[{0:4d}] ".format(t)

            for b_data, b_labels in zip(train_data, train_labels):
                output = self.forward_propagate(b_data)
                self.backpropagate(output, b_labels)
                
                #exit_with_err("FIND ME IN THE CODE, How does weight update is implemented? What is eta?\n")
                
                #It updates the weighs by multiplying the error with the output from itself and the delta 
                #from the next node in the network
                #eta is how aggressive the network "corrects itself" to changes
                self.update_weights(eta=eta)

            if eval_train:
                errs = 0
                for b_data, b_labels in zip(train_data, train_labels):
                    output = self.forward_propagate(b_data)
                    yhat = np.argmax(output, axis=1)
                    errs += np.sum(1-b_labels[np.arange(len(b_labels)), yhat])

                out_str = ("{0} Training error: {1:.5f}".format(out_str,
                                                           float(errs)/N_train))

            if eval_test:
                errs = 0
                for b_data, b_labels in zip(test_data, test_labels):
                    output = self.forward_propagate(b_data)
                    yhat = np.argmax(output, axis=1)
                    errs += np.sum(1-b_labels[np.arange(len(b_labels)), yhat])

                out_str = ("{0} Test error: {1:.5f}").format(out_str,
                                                       float(errs)/N_test)

            print (out_str)


In [50]:
def label_to_bit_vector(labels, nbits):
    print((labels.shape[0], nbits))
    bit_vector = np.zeros((labels.shape[0], nbits))
    print(bit_vector)
    for i in range(labels.shape[0]):
        bit_vector[i, labels[i]] = 1.0

    return bit_vector

In [51]:
s=['Hip-Hop','Pop','Folk','Experimental','Rock','International','Electronic','Instrumental']

mydict={}
i = 0
for item in s:
    if(i>0 and item in mydict):
        continue
    else:    
       mydict[item] = i
       i = i+1
mydict

{'Hip-Hop': 0,
 'Pop': 1,
 'Folk': 2,
 'Experimental': 3,
 'Rock': 4,
 'International': 5,
 'Electronic': 6,
 'Instrumental': 7}

In [52]:
def genre_to_bit_vector(genres, nbits):
        
    print((genres.shape[0], nbits))
    bit_vector = np.zeros((genres.shape[0], nbits))
    
    print(bit_vector)
    nr_genres = 0
    i =  0
    while nr_genres<genres.shape[0]:
        try:
            print(str(nr_genres) + " " + str(genres[i]) )
            bit_vector[nr_genres, mydict[genres[i]]] = 1.0
            i += 1
            nr_genres += 1
        except KeyError:
            i += 1
    return bit_vector

In [53]:
def create_batches(data, labels, batch_size, create_bit_vector=False):
    N = data.shape[0]
    print("This is : " + N)
    print ("Batch size {0}, the number of examples {1}.".format(batch_size,N))

    if N % batch_size != 0:
        print ("Warning in create_minibatches(): Batch size {0} does not " \
              "evenly divide the number of examples {1}.".format(batch_size,N))
    chunked_data = []
    chunked_labels = []
    idx = 0
    while idx + batch_size <= N:
        chunked_data.append(data[idx:idx+batch_size, :])
        if not create_bit_vector:
            chunked_labels.append(labels[idx:idx+batch_size])
        else:
            bit_vector = genre_to_bit_vector(labels[idx:idx+batch_size], 8)
            chunked_labels.append(bit_vector)

        idx += batch_size

    return chunked_data, chunked_labels


In [54]:
def prepare_for_backprop(batch_size, Train_images, Train_labels, Valid_images, Valid_labels):
    
    print ("Creating data...")
    batched_train_data, batched_train_labels = create_batches(Train_images, Train_labels,
                                              batch_size,
                                              create_bit_vector=True)
    batched_valid_data, batched_valid_labels = create_batches(Valid_images, Valid_labels,
                                              batch_size,
                                              create_bit_vector=True)
    print ("Done!")


    return batched_train_data, batched_train_labels,  batched_valid_data, batched_valid_labels



In [55]:
tracks = utils.load('./fma_metadata/tracks.csv')
genres = utils.load('./fma_metadata/genres.csv')
features = utils.load('./fma_metadata/features.csv')
echonest = utils.load('./fma_metadata/echonest.csv')

np.testing.assert_array_equal(features.index, tracks.index)
assert echonest.index.isin(tracks.index).all()

/home/elias/anaconda3/envs/D7041E/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: specifying 'categories' or 'ordered' in .astype() is deprecated; pass a CategoricalDtype instead
  """Entry point for launching an IPython kernel.


In [56]:
def spectogram(songID,resample=False ,sampling=44100, plot = True):
    filepath = utils.get_audio_path('./fma_small/', songID)
    try:
        x, sr = librosa.load(filepath, sr=None, mono=True)  # kaiser_fast
    except FileNotFoundError:
        return -1
        
    
    if(resample):
        x = librosa.resample(x, sr, sampling)
        sr = sampling
    spec = librosa.feature.melspectrogram(y=x, sr=sr)
    
    if(plot):
        plt.figure(figsize=(10, 4))
        librosa.display.specshow(librosa.power_to_db(spec, ref=np.max), y_axis='mel', fmax=sr, x_axis='time')
        plt.colorbar(format='%+2.0f dB')
        plt.title('Mel spectrogram')
        plt.tight_layout()
    return spec

In [ ]:
#(Xtr, Ltr), (X_test, L_test)=mnist.load_data()

#Xtr = Xtr.reshape(60000, 784)
#X_test = X_test.reshape(10000, 784)
#Xtr = Xtr.astype('float32')
#X_test = X_test.astype('float32')
#Xtr /= 255
#X_test /= 255
#print(Xtr.shape[0], 'train samples')
#print(X_test.shape[0], 'test samples')


In [57]:
small = tracks['set', 'subset'] <= 'small'

train = tracks['set', 'split'] == 'training'
val = tracks['set', 'split'] == 'validation'
test = tracks['set', 'split'] == 'test'




X_test = features.loc[small & test, 'mfcc']


#genres = tracks.loc[small , ('track', 'genre_top')]


In [59]:
Xtr = features.loc[small & train, 'mfcc']

In [61]:
Ltr = tracks.loc[small & train, ('track', 'genre_top')]

In [63]:
L_test = tracks.loc[small & test, ('track', 'genre_top')]

In [13]:
y_train
#y_train=y_train.values
#y_train=y_train._array_()
type(y_train)
y_train.shape
y_train[2]

'Hip-Hop'

In [43]:
y = y_train[:10]

In [44]:
genre_to_bit_vector(y,8)

(10, 8)
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
0 Hip-Hop
1 Hip-Hop
2 Pop
3 Folk
4 Folk
5 Folk
6 Folk
7 Folk
8 Folk
9 Folk


array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.]])

In [21]:
X_train.shape
#X_train = X_train.values
type(X_train)
X_train.shape

(6400, 140)

# Default activation eta = 0.005

In [64]:
batch_size=100;

train_data, train_labels, valid_data, valid_labels=prepare_for_backprop(batch_size, Xtr, Ltr, X_test, L_test)

mlp = MultiLayerPerceptron(layer_config=[140, 70, 70, 8], batch_size=batch_size)

mlp.evaluate(train_data, train_labels, valid_data, valid_labels,eta=0.005,
             eval_train=True)

print("Done:)\n")

Creating data...
Batch size 100, the number of examples 6400.


TypeError: '(slice(0, 100, None), slice(None, None, None))' is an invalid key